### ISSUE TITLE
Installing development version of `r2dii.data` causes regression tests to fail

### ISSUE THREAD

**Issue by jdhoffa** [2DegreesInvesting/r2dii.analysis#154] opened 2020-07-29 14:38 UTC
With the most recent development version of `r2dii.data`, I get a large number of errors in our regression tests:
<img width="637" alt="Screen Shot 2020-07-29 at 4 36 49 PM" src="https://user-images.githubusercontent.com/8741309/88813851-b4c22a00-d1b9-11ea-8bb9-8244c81bc1e4.png">

however, with the CRAN version of `r2dii.data`, everything passes fine: 
<img width="133" alt="Screen Shot 2020-07-29 at 4 37 57 PM" src="https://user-images.githubusercontent.com/8741309/88814007-dd4a2400-d1b9-11ea-9534-b0c389adaf2b.png">

**Comment by maurolepore** [comment] 2020-07-29 15:16
It seems that the problem is that you and I have different verisions. I was behind.

``` r
packageVersion("r2dii.data")
#> [1] '0.1.1'
```

<sup>Created on 2020-07-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>


We should be fine if we both use the devel version, and refresh the regression references. Shall we try that?

**Comment by maurolepore** [comment] 2020-07-29 15:21
I updated to the version of r2dii.data on github and I get an error but only one. Not sure if that is what you expect. Maybe ensure you install from github instead of locally (as your local version of r2dii.data maybe pointing to a different commit).

![image](https://user-images.githubusercontent.com/5856545/88819116-2c299680-d185-11ea-8d0b-21d3a67781f3.png)

**Comment by jdhoffa** [comment] 2020-07-30 09:05
Ya so the "SIC" codes are only in the dev version of `r2dii.data` so that makes sense. You would need to update that regression test.

**Comment by maurolepore** [comment] 2020-07-30 11:12
Thanks. Does this close the issue?

**Comment by jdhoffa** [comment] 2020-07-30 12:55
I think so... we'll have to update the regression value to include "SIC" at some point

**Comment by maurolepore** [comment] 2020-07-31 11:04
It seems there is some other problem too, one that is not about SIC but about the summaries precision. 

![image](https://user-images.githubusercontent.com/5856545/89029275-a8da8300-d2f3-11ea-84a7-3c39e8371931.png)

**Comment by jdhoffa** [comment] 2020-07-31 11:38
@maurolepore happy to do this with you today at some point if you'd like!

**Comment by maurolepore** [comment] 2020-07-31 14:41
The problem seems to be on my end. The regression files only change on my system. On Docker I get the same regression files as GitHub actions, and Jackson. I'll close the issue because it seems to be not in the package.

**Closed by maurolepore** 2020-07-31 14:41 UTC
Labels: bug
